name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      REMOTE_DIR: '~/igy-prod/'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        run: |
          docker buildx build . --file Dockerfile --tag $DOCKER_REPO:latest
          docker tag $DOCKER_REPO:latest $DOCKER_USER/$DOCKER_REPO:latest
          docker push $DOCKER_USER/$DOCKER_REPO:latest

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 1111 -t ed25519 "$SSH_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy to production
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_ed25519 -p 1111 "$SSH_USER@$SSH_HOST" << EOF
            cd "$REMOTE_DIR"
            docker-compose down
            docker pull $DOCKER_USER/$DOCKER_REPO:latest
            docker-compose up -d
            echo "Deployment completed successfully."
          EOF
