name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-${{date +%F_%T}}

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_REPO: ${{secrets.DOCKER_REPO}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag ${{secrets.DOCKER_REPO}}:${{date +%F_%T}}

      - name: Tag the Docker image
        run: docker tag ${{secrets.DOCKER_REPO}}:${{date +%F_%T}} ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${{date +%F_%T}}

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${{date +%F_%T}}
